stages:
  stage_01: 
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts01.txt

  stage_02: 
    cmd: python stage_02.py
    deps:
      - artifacts01.txt
      - stage_02.py
